/tv2x_bridge:
  ros__parameters:
    general:
      v2x_interface: "wlan1"
      cam_asn: "cam.asn"
      denm_asn: "denm.asn"
      trace: "obu.json"
      mac: "b4:b5:b6:c4:11:49"
    topic:
      cam: "/v2x/cam"
      denm: "/v2x/denm"
